### ISSUE TITLE
中文项目的 bot 应该标为 bot 吧

### ISSUE THREAD

**Issue by stevending1st** [OpenSourceWin/hacking-force#2]
如题

例：
1715 行：
metersphere-bot | 31.28 |   | 否 | 中国 | FIT2CLOUD 飞致云旗下 MeterSphere 项目（https://github.com/metersphere/metersphere）用于自动处理 pull request 的账号
-- | -- | -- | -- | -- | -- |

**Comment by frank-zsy** [comment]
是的，已修正~感谢
