### ISSUE TITLE
有关中国开源码力榜的评选问题

### ISSUE THREAD

**Issue by YuChen-C4** [OpenSourceWin/hacking-force#4]
请问“中国开源码力榜”的评选中，开发者影响力具体是如何计算的？
方便问一下 Apache ShardingSphere 的张亮老师能否入榜，个人认为张亮老师的开发者影响力应该不低，这是他的 GitHub 个人主页地址：https://github.com/terrymanu

**Comment by sunshineg** [comment]
hi 你好，感谢反馈，通过公开的 [TOP 1W](https://docs.qq.com/sheet/DQWpIT1NLZlllVlha) 文档发现张亮是在名单中的，之前没有被发掘出来，现在已经进行了标注，刚刚也已经有社区开发者提交了 [PR](https://github.com/OpenSourceWin/OpenSourceWin.github.io/pull/29) 代码官网上应该很快就会更新出来。

在 1W 个名单中标注出可能的中国开发者是一个大工程，也欢迎一起参与哈。

**Comment by sunshineg** [comment]
官网上已经可以查看 https://opensource.win/terrymanu/ ，@terrymanu 本人可以通过参考 [OpenSourceWin.github.io](https://github.com/OpenSourceWin/OpenSourceWin.github.io) 项目协作流程优化自己在官网的展示文案，可参考案例 [Huan ](https://github.com/OpenSourceWin/OpenSourceWin.github.io/commits?author=huan) https://opensource.win/huan/

**Comment by YuChen-C4** [comment]
好的，能够看到了，麻烦啦🤝
