### ISSUE TITLE
榜单人员提名

### ISSUE THREAD

**Issue by YuChen-C4** [OpenSourceWin/hacking-force#6]

**Comment by YuChen-C4** [comment]
您好，
我看到公开的表单中，ShardingSphere 的吴伟杰老师（GitHub ID ：TeslaCN）应该能够加入到榜单中吧，麻烦相关负责同学帮忙看一下，公开表单 5543.

**Comment by sunshineg** [comment]
hi @YuChen-C4 感谢反馈

我让项目组小伙伴 @sy-records 同学协助一起 check 一下 :)

**Comment by sy-records** [comment]
TeslaCN 的排名是 67 ~

**Comment by sunshineg** [comment]
hi @YuChen-C4 官网已经更新 https://opensource.win/TeslaCN/ 可以让作者通过提 pr 的方式更新自己的 profile 

- 案例参考1 https://opensource.win/huan/
- 案例参考2 https://opensource.win/AlexV525/
